import org.apache.dubbo.config.spring.beans.factory.config.DubboConfigEarlyRegistrationPostProcessor.DubboConfigEarlyInitializationPostProcessor;
public class FunctionUse855 {
public void funcUse() {
DubboConfigEarlyInitializationPostProcessor dubboconfigearlyinitializationpostprocessor = new DubboConfigEarlyInitializationPostProcessor();
dubboconfigearlyinitializationpostprocessor.processBeforeInitialization(null,null);
}
}